### ISSUE TITLE
Technologia użyta w tym projekcie

### ISSUE THREAD

**Issue by ghost** [lotego-co-godo/sokoban#1]
Chciałbym przedyskutować, z jakiej technologii będziemy korzystać przy tym projekcie (czyli jaki język, z jakich bibliotek będziemy korzystać, itp.).

Tak jak zaproponował @Marco361, można by napisać to w języku **Java**. Dla mnie nie jest to większym problemem, ale nie wiem, jak wy stoicie z **Javą** i **programowaniem obiektowym**.

Jeśli wybierzemy Javę, to do wyświetlania grafiki użyłbym biblioteki **LWJGL**.

Napiszcie w komentarzach pod tym issue czy takie rozwiązanie wam odpowiada lub zaproponujcie jakieś alternatywy.

**Comment by MrCoookie** [comment]
Po zapoznaniu się z tematem wykonanie tego w pythonie byłoby zbytnio czasochłonne bo biblioteka PyGame jest zbyt potężna żeby to tak o ogarnąć i jeszcze sie nauczyc a co dopiero zrozumieć.

**Comment by ghost** [comment]
Jakiejś biblioteki potrzebujemy tylko do samego renderowania, resztę możemy ogarnąć sami przy tak prostej grze. W **PyGamie** renderowanie **Spritów** wydaję się dość proste ([link](https://www.pygame.org/docs/ref/sprite.html)), więc jeszcze nie skreślałbym tego **Pythona**, chociaż tutaj problemem jest to, że robienie gier w **Pythonie** nie jest zbyt popularne, więc mógłby być problem z szukaniem informacji.

W **Javie** będzie o wiele prościej pod tym względem, tylko sam język jest dość trudny, bo trzeba dobrze rozumieć **klasy** i **obiekty**.

**Comment by ghost** [comment]
Zgodnie z ustaleniami z calla, będziemy używać języka **JavaScript**.
